export const BusinessCommencedOptions = [
  { key: '1', text: '1 Month', value: '1 Month' },
  { key: '2', text: '2 Month', value: '2 Month' },
  { key: '3', text: '3 Month', value: '3 Month' },
  { key: '4', text: '4 Month', value: '4 Month' },
  { key: '5', text: '5 Month', value: '5 Month' },
  { key: '6', text: '6 Month', value: '6 Month' },
  { key: '7', text: '7 Month', value: '7 Month' },
  { key: '8', text: '8 Month', value: '8 Month' },
  { key: '9', text: '9 Month', value: '9 Month' },
  { key: '10', text: '10 Month', value: '10 Month' },
  { key: '11', text: '11 Month', value: '11 Month' },
  { key: '12', text: '1 year', value: '1 year' },
  { key: '13', text: '1.5 years', value: '1.5 years' },
  { key: '14', text: '2 years', value: '2 years' },
  { key: '15', text: '3 years', value: '3 years' },
  { key: '16', text: '4 years', value: '4 years' },
  { key: '17', text: '5 years', value: '5 years' },
  { key: '18', text: '6 years', value: '6 years' },
  { key: '19', text: '7 years', value: '7 years' },
  { key: '20', text: '8 years', value: '8 years' },
  { key: '21', text: '9 years', value: '9 years' },
  { key: '22', text: '10 years', value: '10 years' },
  { key: '23', text: 'Over 10 years', value: 'Over 10 years' },
  { key: '24', text: '20 years', value: '20 years' },
  { key: '25', text: 'Over 20 years', value: 'Over 20 years' },
  { key: '26', text: '30 years', value: '30 years' },
  { key: '27', text: 'Over 30 years', value: 'Over 30 years' },
  { key: '28', text: '50 years', value: '50 years' }
]
